// Polygon.idl: Polygon의 IDL 소스
//

// 이 파일은 MIDL 도구에 의해 처리되어
// 형식 라이브러리(Polygon.tlb) 및 마샬링 코드를 생성합니다.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(373be9d1-7488-42cc-b776-451592ba7cd6),
	version(1.0),
]
library PolygonLib
{
	importlib("stdole2.tlb");
};

